job0: 
    image: glasslabs/centroot
    stage: test
    script:
        - source /opt/anaconda3/etc/profile.d/conda.sh &&  conda activate base
        - source /opt/root6.18/bin/thisroot.sh
        - python nbtest.py tests/
