image: detlab/centroot:0.1

before_script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/glass-ships/thingstuff.git

test_variable:
  stage: test
  script:
    - cd thingstuff
    - pwd
