image: detlab/centroot:0.1

test_variable:
  stage: test
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/glass-ships/racas-presentation
    - cd racas-presentation
    - pwd
